const orderData = {
	delivery: {
    "data": {
      "actual_pay_total": 34.8,
      "address_info": {
        "ab_strategy": "",
        "address": "上海科技绿洲B区18号楼",
        "address_tip": "",
        "address_tip_reason": 0,
        "address_type": 0,
        "bind_type": 0,
        "categories": [],
        "category": 0,
        "category_icon": "",
        "distance": "",
        "gender": "先生",
        "guide_text": "",
        "house_number": "18楼，外卖科技",
        "id": 935908631,
        "latitude": 31164474,
        "longitude": 121385976,
        "name": "刘光强",
        "phone": "15214313256",
        "recommend_type": 1
      },
      "address_type": 1,
      "app_delivery_tip": "美团快送",
      "box_price_type_tip": "包装费",
      "box_total_price": 4.0,
      "business_type_list": [{
        "selected": 1,
        "self_delivery_agree_selected": 0,
        "self_delivery_agree_url": "",
        "title": "美团配送",
        "type": 0
      }, {
        "selected": 0,
        "self_delivery_agree_selected": 1,
        "self_delivery_agree_url": "",
        "title": "到店自取",
        "type": 1
      }],
      "can_use_coupon_price": 66.8,
      "cautionlist": ["加辣", "不要辣", "不要香菜", "不要葱", "请加餐具", "请带纸巾"],
      "city_delivery_area": {
        "explain_url": "",
        "icon": "",
        "tip": ""
      },
      "coupon_info_list": [{
        "background_highlight": 0,
        "background_highlight_type": 0,
        "bubble_source": 0,
        "count_tip": "",
        "coupon_sign": "",
        "coupon_tip_type": 0,
        "description": "抵用券",
        "discount": "",
        "selected_coupon_id": -1,
        "selected_coupon_view_id": "-1",
        "status_tip": "3张可用",
        "type": 0,
        "usable": 1
      }, {
        "background_highlight": 0,
        "background_highlight_type": 0,
        "bubble_source": 0,
        "count_tip": "",
        "coupon_sign": "",
        "coupon_tip_type": 0,
        "description": "商家代金券",
        "discount": "",
        "selected_coupon_id": 0,
        "selected_coupon_view_id": "0",
        "status_tip": "暂无可用",
        "type": 1,
        "usable": 1
      }],
      "coupon_package": {
        "agreement_url": "",
        "coupon_tip_type": 0,
        "description_title": "",
        "original_price": 0.0,
        "price": 0.0,
        "product_description": "",
        "product_id": "",
        "selected": false,
        "show": false,
        "type": 0
      },
      "default_pay_type": 2,
      "default_tableware_tip": "一起为环保助力",
      "delivery_time_tip": "",
      "delivery_type": 0,
      "delivery_type_icon": "http://p0.meituan.net/aichequan/e6219c6e90c004dba3f3bc9fef5b2f3c2176.png",
      "diners_option": [{
        "count": 99,
        "description": "不需要餐具"
      }, {
        "count": 1,
        "description": "1人"
      }, {
        "count": 2,
        "description": "2人"
      }, {
        "count": 3,
        "description": "3人"
      }, {
        "count": 4,
        "description": "4人"
      }, {
        "count": 5,
        "description": "5人"
      }, {
        "count": 6,
        "description": "6人"
      }, {
        "count": 7,
        "description": "7人"
      }, {
        "count": 8,
        "description": "8人"
      }, {
        "count": 9,
        "description": "9人"
      }, {
        "count": 10,
        "description": "10人"
      }, {
        "count": -10,
        "description": "10人以上"
      }],
      "discount_mutex_info": "",
      "discount_warn_tip": "",
      "discounts": [{
        "coupon_sign": "",
        "icon_url": "http://p1.meituan.net/xianfu/142b6891b51058d8222c6f1fe07e6ec71103.png",
        "id": 25,
        "info": "-￥2",
        "name": "减配送费",
        "reduce_fee": 2.0,
        "type": 0
      }, {
        "coupon_sign": "",
        "icon_url": "http://p0.meituan.net/xianfu/f8bc8dffdbc805878aa3801a33f563cd1001.png",
        "id": 2,
        "info": "-￥33",
        "name": "满减优惠",
        "reduce_fee": 33.0,
        "type": 2
      }],
      "exp_infos": [],
      "expected_arrival_info": {
        "clickable": true,
        "date_type_tip": "立即送出",
        "delivery_time_tip": "",
        "select_view_time": "大约20:28送达",
        "shipping_fee_title": "分时段计价配送费",
        "unixtime": 0,
        "view_shipping_fee": "3.0元"
      },
      "flower_cake_field": {
        "caution_values": [],
        "customer_values": [],
        "default_values": [],
        "detail_hint": "",
        "hint": ""
      },
      "foodlist": [{
        "act_info_list": [],
        "activity_extra": "",
        "activity_tag": "discount",
        "attrs": [],
        "cart_id": 0,
        "count": 1,
        "description_tip": "",
        "food_label_url": "",
        "id": 974362156,
        "name": "可乐（大杯）",
        "original_price": 9.0,
        "package_id": 0,
        "picture": "http://p1.meituan.net/wmproduct/9f42f50dd212c42ce9f9047a2e1ad70a1719785.jpg",
        "price": 9.0,
        "spec": "",
        "spu_id": 896335846,
        "sub_total_price": 9.0,
        "unit": "份"
      }, {
        "act_info_list": [],
        "activity_extra": "",
        "activity_tag": "discount",
        "attrs": [],
        "cart_id": 0,
        "count": 1,
        "description_tip": "",
        "food_label_url": "",
        "id": 809821936,
        "name": "老北京鸡肉卷",
        "original_price": 13.9,
        "package_id": 0,
        "picture": "http://p0.meituan.net/wmproduct/0dee54010c6afc1e72e59e2871d70f513002475.png",
        "price": 13.9,
        "spec": "",
        "spu_id": 747128142,
        "sub_total_price": 13.9,
        "unit": "个"
      }, {
        "act_info_list": [],
        "activity_extra": "",
        "activity_tag": "discount",
        "attrs": [],
        "cart_id": 0,
        "count": 1,
        "description_tip": "",
        "food_label_url": "",
        "id": 813753751,
        "name": "香辣鸡排（香辣味）",
        "original_price": 25.0,
        "package_id": 0,
        "picture": "http://p0.meituan.net/wmproduct/7adc37295e9d676b531167ae983b47993561681.png",
        "price": 25.0,
        "spec": "",
        "spu_id": 750763135,
        "sub_total_price": 25.0,
        "unit": "份"
      }, {
        "act_info_list": [],
        "activity_extra": "",
        "activity_tag": "discount",
        "attrs": [],
        "cart_id": 0,
        "count": 1,
        "description_tip": "",
        "food_label_url": "",
        "id": 809829128,
        "name": "香辣鸡腿堡",
        "original_price": 14.9,
        "package_id": 0,
        "picture": "http://p1.meituan.net/wmproduct/372473766b64be5f21e376e3dd9ff9052854075.png",
        "price": 14.9,
        "spec": "",
        "spu_id": 747123773,
        "sub_total_price": 14.9,
        "unit": "份"
      }],
      "has_invoice": 0,
      "insurance": {
        "cost": 0.0,
        "description": "",
        "insurance_confirm_desc": "",
        "insurance_detail_url": "",
        "insurance_explain_url": "",
        "insurance_icon": "",
        "insurance_name": "",
        "insurance_reason_code": 0,
        "insurance_selected": 0,
        "purchase_desc": "",
        "purchase_type": 0,
        "show": 0,
        "tips": ""
      },
      "invoice_support": 0,
      "invoice_title": "",
      "invoice_type": 0,
      "is_assign_delivery_time": 1,
      "min_invoice_price": 0.0,
      "mt_delivery_info": {
        "mt_delivery_tags": [],
        "mt_delivery_tip": ""
      },
      "no_product_reminds": [],
      "order_delivery_tip": {
        "explain_url": "",
        "text": "",
        "type": 0
      },
      "order_preview_tip": {
        "icon_url": "",
        "text": ""
      },
      "order_template_type": 0,
      "original_price": 69.8,
      "pay_type_tip": "",
      "payment_info": [{
        "display_switch": 1,
        "payment_extra_info": "",
        "payment_tip": "",
        "payment_type": 2
      }],
      "phone_field": {
        "caution_values": [],
        "customer_values": [],
        "default_values": [],
        "detail_hint": "",
        "hint": ""
      },
      "poi_close_notification": {
        "nOT_SHOW_NOTIFICATION": 0,
        "remain_time": 0,
        "sHOW_NOTIFICATION": 0,
        "visible": 0
      },
      "poi_icon": "http://p0.meituan.net/waimaipoi/6126e47d09268a4b0bc418488d693a9038058.jpg",
      "poi_name": "正新汉堡·炸鸡（东兰餐厅店）",
      "poi_project_description": "",
      "poi_project_description_url": "",
      "pre_order": 0,
      "privacy_service": {
        "new_feature_guide_desc": "美团已为您开启号码保护，保护您的隐私",
        "privacy_close_desc": "对商家、骑手隐藏您的真实手机号，保护您的隐私",
        "privacy_desc": "对商家、骑手隐藏您的真实手机号，保护您的隐私",
        "privacy_explain_url": "http://i.waimai.meituan.com/node/static/privacy-rules",
        "privacy_icon": "https://p0.meituan.net/dptakeaway/b8b97f34-7fd6-41af-98f0-dc7dc1d122a7.jpg",
        "privacy_open_desc": "对商家、骑手隐藏您的真实手机号，保护您的隐私",
        "privacy_open_guide_desc": "",
        "privacy_selected": 1,
        "privacy_selected_desc": "",
        "privacy_title": "号码保护",
        "show": 1
      },
      "product_remind_tip": "",
      "product_weight_tip": "",
      "reduced_shipping_fee": 0.0,
      "remark_field": {
        "caution_values": [],
        "customer_values": [],
        "default_values": ["不吃辣", "少放辣", "多放辣", "不吃蒜", "不吃香菜", "不吃葱"],
        "detail_hint": "请输入口味、偏好等要求，不支持额外代购其他物品哦~",
        "hint": "口味、偏好等要求"
      },
      "remind_infos": [],
      "shipping_detail": [],
      "shipping_fee": 3.0,
      "shipping_fee_discount_tip": "",
      "shipping_fee_update_reason": "",
      "shipping_rule_url": "",
      "shop_cart_id": "",
      "show_steal_entry": 0,
      "tableware_advocate_tip": "美团外卖倡导：减少使用一次性餐具，为环境保护出份力！",
      "taxpayer_id_number": "",
      "template_type": 0,
      "tip": "",
      "token": "E02B6C956C4942098BB1547DF1BBC942",
      "total": 34.8,
      "vip_entrance": {
        "click_url": "",
        "entrance_visible": 0,
        "nOT_SHOW_VIP_ENTRANCE": 0,
        "sHOW_VIP_ENTRANCE": 0,
        "title": ""
      }
    },
    "code": 0,
    "msg": "成功"
  },
  pick: {
    "data": {
      "actual_pay_total": 26.8,
      "address_info": {
        "ab_strategy": "",
        "address": "上海市闵行区龙茗路1689号",
        "address_tip": "请您在明天 03:32之前到店自取商品。如超时请提前与商家沟通，否则商家有权丢弃该商品并拒绝退款",
        "address_tip_reason": 0,
        "address_type": 1,
        "bind_type": 0,
        "categories": [],
        "category": 0,
        "category_icon": "",
        "distance": "198m",
        "gender": "",
        "guide_text": "",
        "house_number": "",
        "id": 0,
        "latitude": 31151651,
        "longitude": 121382437,
        "name": "",
        "phone": "15214313256",
        "recommend_type": 1
      },
      "address_type": 1,
      "app_delivery_tip": "",
      "box_price_type_tip": "包装费",
      "box_total_price": 3.0,
      "business_type_list": [{
        "selected": 0,
        "self_delivery_agree_selected": 0,
        "self_delivery_agree_url": "",
        "title": "美团配送",
        "type": 0
      }, {
        "selected": 1,
        "self_delivery_agree_selected": 1,
        "self_delivery_agree_url": "https://i.waimai.meituan.com/node/fetchrule",
        "title": "到店自取",
        "type": 1
      }],
      "can_use_coupon_price": 56.8,
      "cautionlist": ["加辣", "不要辣", "不要香菜", "不要葱", "请加餐具", "请带纸巾"],
      "city_delivery_area": {
        "explain_url": "",
        "icon": "",
        "tip": ""
      },
      "coupon_info_list": [{
        "background_highlight": 0,
        "background_highlight_type": 0,
        "bubble_source": 0,
        "count_tip": "",
        "coupon_sign": "",
        "coupon_tip_type": 0,
        "description": "抵用券",
        "discount": "",
        "selected_coupon_id": 0,
        "selected_coupon_view_id": "0",
        "status_tip": "暂无可用",
        "type": 0,
        "usable": 1
      }, {
        "background_highlight": 0,
        "background_highlight_type": 0,
        "bubble_source": 0,
        "count_tip": "",
        "coupon_sign": "",
        "coupon_tip_type": 0,
        "description": "商家代金券",
        "discount": "",
        "selected_coupon_id": 0,
        "selected_coupon_view_id": "0",
        "status_tip": "暂无可用",
        "type": 1,
        "usable": 1
      }],
      "coupon_package": {
        "agreement_url": "",
        "coupon_tip_type": 0,
        "description_title": "",
        "original_price": 0.0,
        "price": 0.0,
        "product_description": "",
        "product_id": "",
        "selected": false,
        "show": false,
        "type": 0
      },
      "default_pay_type": 2,
      "default_tableware_tip": "一起为环保助力",
      "delivery_time_tip": "",
      "delivery_type": 0,
      "delivery_type_icon": "http://p1.meituan.net/aichequan/d7b1f1f28a2523c45ffb34555f894cb22489.png",
      "diners_option": [{
        "count": 99,
        "description": "不需要餐具"
      }, {
        "count": 1,
        "description": "1人"
      }, {
        "count": 2,
        "description": "2人"
      }, {
        "count": 3,
        "description": "3人"
      }, {
        "count": 4,
        "description": "4人"
      }, {
        "count": 5,
        "description": "5人"
      }, {
        "count": 6,
        "description": "6人"
      }, {
        "count": 7,
        "description": "7人"
      }, {
        "count": 8,
        "description": "8人"
      }, {
        "count": 9,
        "description": "9人"
      }, {
        "count": 10,
        "description": "10人"
      }, {
        "count": -10,
        "description": "10人以上"
      }],
      "discount_mutex_info": "",
      "discount_warn_tip": "到店自取仅享受部分优惠",
      "discounts": [{
        "coupon_sign": "",
        "icon_url": "http://p0.meituan.net/xianfu/f8bc8dffdbc805878aa3801a33f563cd1001.png",
        "id": 2,
        "info": "-￥30",
        "name": "满减优惠",
        "reduce_fee": 30.0,
        "type": 2
      }],
      "exp_infos": [],
      "expected_arrival_info": {
        "clickable": true,
        "date_type_tip": "自取时间",
        "delivery_time_tip": "",
        "select_view_time": "23:33",
        "shipping_fee_title": "分时段计价配送费",
        "unixtime": 1537975980,
        "view_shipping_fee": "0.0元"
      },
      "flower_cake_field": {
        "caution_values": [],
        "customer_values": [],
        "default_values": [],
        "detail_hint": "",
        "hint": ""
      },
      "foodlist": [{
        "act_info_list": [],
        "activity_extra": "",
        "activity_tag": "discount",
        "attrs": [],
        "cart_id": 0,
        "count": 1,
        "description_tip": "",
        "food_label_url": "",
        "id": 809821936,
        "name": "老北京鸡肉卷",
        "original_price": 13.9,
        "package_id": 0,
        "picture": "http://p0.meituan.net/wmproduct/0dee54010c6afc1e72e59e2871d70f513002475.png",
        "price": 13.9,
        "spec": "",
        "spu_id": 747128142,
        "sub_total_price": 13.9,
        "unit": "个"
      }, {
        "act_info_list": [],
        "activity_extra": "",
        "activity_tag": "discount",
        "attrs": [],
        "cart_id": 0,
        "count": 1,
        "description_tip": "",
        "food_label_url": "",
        "id": 813753751,
        "name": "香辣鸡排（香辣味）",
        "original_price": 25.0,
        "package_id": 0,
        "picture": "http://p0.meituan.net/wmproduct/7adc37295e9d676b531167ae983b47993561681.png",
        "price": 25.0,
        "spec": "",
        "spu_id": 750763135,
        "sub_total_price": 25.0,
        "unit": "份"
      }, {
        "act_info_list": [],
        "activity_extra": "",
        "activity_tag": "discount",
        "attrs": [],
        "cart_id": 0,
        "count": 1,
        "description_tip": "",
        "food_label_url": "",
        "id": 809829128,
        "name": "香辣鸡腿堡",
        "original_price": 14.9,
        "package_id": 0,
        "picture": "http://p1.meituan.net/wmproduct/372473766b64be5f21e376e3dd9ff9052854075.png",
        "price": 14.9,
        "spec": "",
        "spu_id": 747123773,
        "sub_total_price": 14.9,
        "unit": "份"
      }],
      "has_invoice": 0,
      "insurance": {
        "cost": 0.0,
        "description": "",
        "insurance_confirm_desc": "",
        "insurance_detail_url": "",
        "insurance_explain_url": "",
        "insurance_icon": "",
        "insurance_name": "",
        "insurance_reason_code": 0,
        "insurance_selected": 0,
        "purchase_desc": "",
        "purchase_type": 0,
        "show": 0,
        "tips": ""
      },
      "invoice_support": 0,
      "invoice_title": "",
      "invoice_type": 0,
      "is_assign_delivery_time": 1,
      "min_invoice_price": 0.0,
      "mt_delivery_info": {
        "mt_delivery_tags": [],
        "mt_delivery_tip": ""
      },
      "no_product_reminds": [],
      "order_delivery_tip": {
        "explain_url": "",
        "text": "",
        "type": 0
      },
      "order_preview_tip": {
        "icon_url": "",
        "text": ""
      },
      "order_template_type": 0,
      "original_price": 56.8,
      "pay_type_tip": "",
      "payment_info": [{
        "display_switch": 1,
        "payment_extra_info": "",
        "payment_tip": "",
        "payment_type": 2
      }],
      "phone_field": {
        "caution_values": [],
        "customer_values": [],
        "default_values": [],
        "detail_hint": "",
        "hint": ""
      },
      "poi_close_notification": {
        "nOT_SHOW_NOTIFICATION": 0,
        "remain_time": 0,
        "sHOW_NOTIFICATION": 0,
        "visible": 0
      },
      "poi_icon": "http://p0.meituan.net/waimaipoi/6126e47d09268a4b0bc418488d693a9038058.jpg",
      "poi_name": "正新汉堡·炸鸡（东兰餐厅店）",
      "poi_project_description": "",
      "poi_project_description_url": "",
      "pre_order": 0,
      "privacy_service": {
        "new_feature_guide_desc": "",
        "privacy_close_desc": "",
        "privacy_desc": "",
        "privacy_explain_url": "",
        "privacy_icon": "",
        "privacy_open_desc": "",
        "privacy_open_guide_desc": "",
        "privacy_selected": 0,
        "privacy_selected_desc": "",
        "privacy_title": "",
        "show": 0
      },
      "product_remind_tip": "",
      "product_weight_tip": "",
      "reduced_shipping_fee": 5.0,
      "remark_field": {
        "caution_values": [],
        "customer_values": [],
        "default_values": ["不吃辣", "少放辣", "多放辣", "不吃蒜", "不吃香菜", "不吃葱"],
        "detail_hint": "请输入口味、偏好等要求，不支持额外代购其他物品哦~",
        "hint": "口味、偏好等要求"
      },
      "remind_infos": [{
        "behavior_type": 2,
        "icon": "",
        "remind_content": "到店自取仅享受部分优惠",
        "statistics_code": 0,
        "support_type": 2
      }],
      "shipping_detail": [],
      "shipping_fee": 0.0,
      "shipping_fee_discount_tip": "",
      "shipping_fee_update_reason": "",
      "shipping_rule_url": "",
      "shop_cart_id": "",
      "show_steal_entry": 0,
      "tableware_advocate_tip": "美团外卖倡导：减少使用一次性餐具，为环境保护出份力！",
      "taxpayer_id_number": "",
      "template_type": 0,
      "tip": "",
      "token": "0A2822F209F54252983E66177E2DBE78",
      "total": 26.8,
      "vip_entrance": {
        "click_url": "",
        "entrance_visible": 0,
        "nOT_SHOW_VIP_ENTRANCE": 0,
        "sHOW_VIP_ENTRANCE": 0,
        "title": ""
      }
    },
    "code": 0,
    "msg": "成功"
  }
}

export {orderData}