const searchData = {
  data: {
    "data": {
      "labels": [{
        "click_url": "",
        "label_id": 0,
        "label_name": "麻辣烫",
        "label_pic_url": "",
        "label_type": 12002,
        "search_keyword": "麻辣烫",
        "show_time_range": "",
        "wm_poi_id": 0,
        "wm_poi_view_id": ""
      }, {
        "click_url": "",
        "label_id": 0,
        "label_name": "瘦肉粥",
        "label_pic_url": "",
        "label_type": 12001,
        "search_keyword": "瘦肉粥",
        "show_time_range": "",
        "wm_poi_id": 0,
        "wm_poi_view_id": ""
      }, {
        "click_url": "",
        "label_id": 0,
        "label_name": "卤肉饭",
        "label_pic_url": "",
        "label_type": 12001,
        "search_keyword": "卤肉饭",
        "show_time_range": "",
        "wm_poi_id": 0,
        "wm_poi_view_id": ""
      }, {
        "click_url": "",
        "label_id": 0,
        "label_name": "土豆丝",
        "label_pic_url": "",
        "label_type": 12001,
        "search_keyword": "土豆丝",
        "show_time_range": "",
        "wm_poi_id": 0,
        "wm_poi_view_id": ""
      }, {
        "click_url": "",
        "label_id": 0,
        "label_name": "小炒肉",
        "label_pic_url": "",
        "label_type": 12001,
        "search_keyword": "小炒肉",
        "show_time_range": "",
        "wm_poi_id": 0,
        "wm_poi_view_id": ""
      }, {
        "click_url": "",
        "label_id": 0,
        "label_name": "冷面",
        "label_pic_url": "",
        "label_type": 12001,
        "search_keyword": "冷面",
        "show_time_range": "",
        "wm_poi_id": 0,
        "wm_poi_view_id": ""
      }, {
        "click_url": "",
        "label_id": 0,
        "label_name": "粉丝汤",
        "label_pic_url": "",
        "label_type": 12001,
        "search_keyword": "粉丝汤",
        "show_time_range": "",
        "wm_poi_id": 0,
        "wm_poi_view_id": ""
      }, {
        "click_url": "",
        "label_id": 0,
        "label_name": "空心菜",
        "label_pic_url": "",
        "label_type": 12001,
        "search_keyword": "空心菜",
        "show_time_range": "",
        "wm_poi_id": 0,
        "wm_poi_view_id": ""
      }, {
        "click_url": "",
        "label_id": 0,
        "label_name": "烤翅",
        "label_pic_url": "",
        "label_type": 12001,
        "search_keyword": "烤翅",
        "show_time_range": "",
        "wm_poi_id": 0,
        "wm_poi_view_id": ""
      }, {
        "click_url": "",
        "label_id": 0,
        "label_name": "鸡排",
        "label_pic_url": "",
        "label_type": 12002,
        "search_keyword": "鸡排",
        "show_time_range": "",
        "wm_poi_id": 0,
        "wm_poi_view_id": ""
      }, {
        "click_url": "",
        "label_id": 0,
        "label_name": "薯条",
        "label_pic_url": "",
        "label_type": 12001,
        "search_keyword": "薯条",
        "show_time_range": "",
        "wm_poi_id": 0,
        "wm_poi_view_id": ""
      }, {
        "click_url": "",
        "label_id": 0,
        "label_name": "茄子饭",
        "label_pic_url": "",
        "label_type": 12001,
        "search_keyword": "茄子饭",
        "show_time_range": "",
        "wm_poi_id": 0,
        "wm_poi_view_id": ""
      }, {
        "click_url": "",
        "label_id": 0,
        "label_name": "四季豆",
        "label_pic_url": "",
        "label_type": 12001,
        "search_keyword": "四季豆",
        "show_time_range": "",
        "wm_poi_id": 0,
        "wm_poi_view_id": ""
      }, {
        "click_url": "",
        "label_id": 0,
        "label_name": "金针菇",
        "label_pic_url": "",
        "label_type": 12001,
        "search_keyword": "金针菇",
        "show_time_range": "",
        "wm_poi_id": 0,
        "wm_poi_view_id": ""
      }, {
        "click_url": "",
        "label_id": 0,
        "label_name": "小丸子",
        "label_pic_url": "",
        "label_type": 12001,
        "search_keyword": "小丸子",
        "show_time_range": "",
        "wm_poi_id": 0,
        "wm_poi_view_id": ""
      }],
      "labels_tgt_stids": "",
      "recommend_poi": {
        "is_show_change_button": false,
        "next_page": 0,
        "recommend_poi_list": [],
        "tgt_stids": ""
      },
      "scene_type": "NORMAL",
      "searchHotLabelWithTgtStid": {
        "sceneType": "NORMAL",
        "searchHotLabelList": [{
          "click_url": "",
          "label_id": 0,
          "label_name": "麻辣烫",
          "label_pic_url": "",
          "label_type": 12002,
          "search_keyword": "麻辣烫",
          "show_time_range": "",
          "wm_poi_id": 0,
          "wm_poi_view_id": ""
        }, {
          "click_url": "",
          "label_id": 0,
          "label_name": "瘦肉粥",
          "label_pic_url": "",
          "label_type": 12001,
          "search_keyword": "瘦肉粥",
          "show_time_range": "",
          "wm_poi_id": 0,
          "wm_poi_view_id": ""
        }, {
          "click_url": "",
          "label_id": 0,
          "label_name": "卤肉饭",
          "label_pic_url": "",
          "label_type": 12001,
          "search_keyword": "卤肉饭",
          "show_time_range": "",
          "wm_poi_id": 0,
          "wm_poi_view_id": ""
        }, {
          "click_url": "",
          "label_id": 0,
          "label_name": "土豆丝",
          "label_pic_url": "",
          "label_type": 12001,
          "search_keyword": "土豆丝",
          "show_time_range": "",
          "wm_poi_id": 0,
          "wm_poi_view_id": ""
        }, {
          "click_url": "",
          "label_id": 0,
          "label_name": "小炒肉",
          "label_pic_url": "",
          "label_type": 12001,
          "search_keyword": "小炒肉",
          "show_time_range": "",
          "wm_poi_id": 0,
          "wm_poi_view_id": ""
        }, {
          "click_url": "",
          "label_id": 0,
          "label_name": "冷面",
          "label_pic_url": "",
          "label_type": 12001,
          "search_keyword": "冷面",
          "show_time_range": "",
          "wm_poi_id": 0,
          "wm_poi_view_id": ""
        }, {
          "click_url": "",
          "label_id": 0,
          "label_name": "粉丝汤",
          "label_pic_url": "",
          "label_type": 12001,
          "search_keyword": "粉丝汤",
          "show_time_range": "",
          "wm_poi_id": 0,
          "wm_poi_view_id": ""
        }, {
          "click_url": "",
          "label_id": 0,
          "label_name": "空心菜",
          "label_pic_url": "",
          "label_type": 12001,
          "search_keyword": "空心菜",
          "show_time_range": "",
          "wm_poi_id": 0,
          "wm_poi_view_id": ""
        }, {
          "click_url": "",
          "label_id": 0,
          "label_name": "烤翅",
          "label_pic_url": "",
          "label_type": 12001,
          "search_keyword": "烤翅",
          "show_time_range": "",
          "wm_poi_id": 0,
          "wm_poi_view_id": ""
        }, {
          "click_url": "",
          "label_id": 0,
          "label_name": "鸡排",
          "label_pic_url": "",
          "label_type": 12002,
          "search_keyword": "鸡排",
          "show_time_range": "",
          "wm_poi_id": 0,
          "wm_poi_view_id": ""
        }, {
          "click_url": "",
          "label_id": 0,
          "label_name": "薯条",
          "label_pic_url": "",
          "label_type": 12001,
          "search_keyword": "薯条",
          "show_time_range": "",
          "wm_poi_id": 0,
          "wm_poi_view_id": ""
        }, {
          "click_url": "",
          "label_id": 0,
          "label_name": "茄子饭",
          "label_pic_url": "",
          "label_type": 12001,
          "search_keyword": "茄子饭",
          "show_time_range": "",
          "wm_poi_id": 0,
          "wm_poi_view_id": ""
        }, {
          "click_url": "",
          "label_id": 0,
          "label_name": "四季豆",
          "label_pic_url": "",
          "label_type": 12001,
          "search_keyword": "四季豆",
          "show_time_range": "",
          "wm_poi_id": 0,
          "wm_poi_view_id": ""
        }, {
          "click_url": "",
          "label_id": 0,
          "label_name": "金针菇",
          "label_pic_url": "",
          "label_type": 12001,
          "search_keyword": "金针菇",
          "show_time_range": "",
          "wm_poi_id": 0,
          "wm_poi_view_id": ""
        }, {
          "click_url": "",
          "label_id": 0,
          "label_name": "小丸子",
          "label_pic_url": "",
          "label_type": 12001,
          "search_keyword": "小丸子",
          "show_time_range": "",
          "wm_poi_id": 0,
          "wm_poi_view_id": ""
        }],
        "tgtStidMap": {}
      },
      "search_history_type": []
    },
    "code": 0,
    "msg": "成功"
  }
}

export {searchData}